using System;
using Simulation.Data;
using Simulation.GameTime;
using Zenject;

namespace Simulation.Simulation
{
	/// <summary>
	/// TODO: 
	/// </summary>
	internal interface IEntityIdFactory
	{
		EntityId CreateId(int playerId);
	}
	internal class EntityIdFactory : IEntityIdFactory
	{
		private ITimeService _timeService;

		public EntityIdFactory(ITimeService timeServiceService)
		{
			_timeService = timeServiceService;
		}

		public EntityId CreateId(int playerId)
		{
			// TODO: take playerID into account to generate the entityID to avoid ID clashes
			// TODO: when IDs get generated by different clients at the same time
			// TODO: improve Id generation algorithm
			return new EntityId($"{playerId}{_timeService.GetGameTime()}".GetHashCode());
		}
	}

}
